### ISSUE TITLE
Performance tests / microbenchmarks comparison

### ISSUE THREAD

**Issue by thjaeckle** [leadpony/json-schema-conformance-test#1]
Hi.
I stumbled upon this repository and think it's very helpful in order to choose a JsonSchema validator. So thanks for setting that up 👍 
What I asked myself: You tested the conformance against the official JSON Schema Test Suite.
Did you also run performance tests (e.g. microbenchmarks using JMH) based on the official test suite with the different JsonSchema validator implementations?

I don't have yet a feeling if it would e.g. be a good idea to do JsonSchema based validations for each API call in a service handling several thousands of requests per second.

**Comment by leadpony** [comment]
@thjaeckle
As my personal project, some performance tests are implemented using JMH in [here](https://github.com/leadpony/justify-benchmark). However these tests are not operating on the official JSON Schema Test Suite. The JSON instances in the test suite are too small to take meaningful measurement on the burden of validations.
I do not have any experience in using the JSON Schema for the purpose of validating the requests to Web services. The JMH results show us that 10k to 100k validations can be done in a second, so practically there is no performance problem for adopting the technology.

**Comment by thjaeckle** [comment]
Oh, sorry - did not see/find that other repository.
Your performance tests sound very good, thanks for pointing me in the right direction.
